/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { gsap } from "gsap";
import { useThree } from "@react-three/fiber";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useControls } from "leva";

const CarModel = (props) => {
  gsap.registerPlugin(ScrollTrigger);

  const { nodes, materials } = useGLTF("/car.glb");
  const { camera } = useThree();

  const { carPosition, carRotation } = useControls({
    carPosition: {
      value: {
        x: 0,
        y: 0.3,
        z: 0,
      },
      step: 0.1,
    },
    carRotation: {
      value: {
        x: 0,
        y: -Math.PI / 2,
        z: 0,
      },
      step: 0.1,
    },
  });
  const carRef = useRef();
  useLayoutEffect(() => {
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#section1",
        scrub: true,
        start: "top top",
        endTrigger: "#section6",
        markers: false,
      },
    });

    tl
      //section1
      .to(carRef.current.rotation, { x: Math.PI / 2 })
      //section2
      .to(carRef.current.position, { x: 2 }, "same1")
      .to(carRef.current.rotation, { x: 0.5, y: -1 }, "same1")
      //section3
      .to(carRef.current.position, { x: -2 }, "same2")
      .to(carRef.current.rotation, { x: 0, y: 0.6 }, "same2")
      //section4
      .to(carRef.current.position, { x: -1.5 }, "same3")
      .to(carRef.current.rotation, { x: 0, y: 0.6 }, "same3")
      //section5
      .to(carRef.current.position, { x: 7 }, "same4")
      .to(carRef.current.rotation, { x: 0, y: -5.3 }, "same4");
  }, []);

  return (
    <group
      ref={carRef}
      {...props}
      dispose={null}
      // position-y={0.3}
      // rotation-y={-Math.PI / 2}
      position={[carPosition.x, carPosition.y, carPosition.z]}
      rotation={[carRotation.x, carRotation.y, carRotation.z]}
    >
      <group name="Scene_1" position={[0, -0.31288, 0]} scale={0.51749}>
        <group
          name="Jiotto_Caspita"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.05263}
        >
          <mesh
            name="Object_10"
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.REDFRONTPLandspoilers_pl_tex5}
          />
          <mesh
            name="Object_11"
            castShadow
            receiveShadow
            geometry={nodes.Object_11.geometry}
            material={materials.bac_tex2}
          />
          <mesh
            name="Object_12"
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.black_aluminium}
          />
          <mesh
            name="Object_13"
            castShadow
            receiveShadow
            geometry={nodes.Object_13.geometry}
            material={materials.black_chrome}
          />
          <mesh
            name="Object_14"
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.black_mate}
          />
          <mesh
            name="Object_15"
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials.black_plastic}
          />
          <mesh
            name="Object_16"
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.bolts}
          />
          <mesh
            name="Object_17"
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.bottom}
          />
          <mesh
            name="Object_18"
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.brakedisc_tex5}
          />
          <mesh
            name="Object_19"
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.carbon}
          />
          <mesh
            name="Object_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials.CASPITAspoiler}
          />
          <mesh
            name="Object_20"
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.chrome}
          />
          <mesh
            name="Object_21"
            castShadow
            receiveShadow
            geometry={nodes.Object_21.geometry}
            material={materials.emb_L}
          />
          <mesh
            name="Object_22"
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.emb_R}
          />
          <mesh
            name="Object_23"
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials.grill_2}
          />
          <mesh
            name="Object_24"
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.grill_tex3}
          />
          <mesh
            name="Object_25"
            castShadow
            receiveShadow
            geometry={nodes.Object_25.geometry}
            material={materials.headlight_glass}
          />
          <mesh
            name="Object_26"
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.headlights_tex1}
          />
          <mesh
            name="Object_27"
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.material}
          />
          <mesh
            name="Object_28"
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.intPL}
          />
          <mesh
            name="Object_29"
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials.intlamp_gls_tex2}
          />
          <mesh
            name="Object_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials.JiottoCHRM_tex1}
          />
          <mesh
            name="Object_30"
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.keylock_tex1}
          />
          <mesh
            name="Object_31"
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.kvrrem_tex4}
          />
          <mesh
            name="Object_32"
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.lampBUTTON_pl_tex1}
          />
          <mesh
            name="Object_33"
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.lampBUTTON_tex1}
          />
          <mesh
            name="Object_34"
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.lockRED_tex5}
          />
          <mesh
            name="Object_35"
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.mirrors_tex5}
          />
          <mesh
            name="Object_36"
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.need_for_speed_tex2}
          />
          <mesh
            name="Object_37"
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials.pbronze_tex5}
          />
          <mesh
            name="Object_38"
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials.pchrome_tex5}
          />
          <mesh
            name="Object_39"
            castShadow
            receiveShadow
            geometry={nodes.Object_39.geometry}
            material={materials.pexhachrome_tex5}
          />
          <mesh
            name="Object_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.JiottoPL_tex1}
          />
          <mesh
            name="Object_40"
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials.phole_tex5}
          />
          <mesh
            name="Object_41"
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.plate}
          />
          <mesh
            name="Object_42"
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.pmate_tex5}
          />
          <mesh
            name="Object_43"
            castShadow
            receiveShadow
            geometry={nodes.Object_43.geometry}
            material={materials.ppl_tex5}
          />
          <mesh
            name="Object_44"
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials.radiator2_tex3}
          />
          <mesh
            name="Object_45"
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials.radiator_tex1}
          />
          <mesh
            name="Object_46"
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials.redtriangle_pl_tex1}
          />
          <mesh
            name="Object_47"
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.material_45}
          />
          <mesh
            name="Object_48"
            castShadow
            receiveShadow
            geometry={nodes.Object_48.geometry}
            material={materials.rimins1}
          />
          <mesh
            name="Object_49"
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.rimins2}
          />
          <mesh
            name="Object_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.Jiotto_Caspita_1989_by_Alex_Ka}
          />
          <mesh
            name="Object_50"
            castShadow
            receiveShadow
            geometry={nodes.Object_50.geometry}
            material={materials.spd_gls_tex3}
          />
          <mesh
            name="Object_51"
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials.stickbuttons_pl_tex2}
          />
          <mesh
            name="Object_52"
            castShadow
            receiveShadow
            geometry={nodes.Object_52.geometry}
            material={materials.suport_tex5}
          />
          <mesh
            name="Object_53"
            castShadow
            receiveShadow
            geometry={nodes.Object_53.geometry}
            material={materials.tex1}
          />
          <mesh
            name="Object_54"
            castShadow
            receiveShadow
            geometry={nodes.Object_54.geometry}
            material={materials.tex1_brakelights}
          />
          <mesh
            name="Object_55"
            castShadow
            receiveShadow
            geometry={nodes.Object_55.geometry}
            material={materials.tex2}
          />
          <mesh
            name="Object_56"
            castShadow
            receiveShadow
            geometry={nodes.Object_56.geometry}
            material={materials.tire}
          />
          <mesh
            name="Object_57"
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={materials.tire_L}
          />
          <mesh
            name="Object_58"
            castShadow
            receiveShadow
            geometry={nodes.Object_58.geometry}
            material={materials.tire_R}
          />
          <mesh
            name="Object_59"
            castShadow
            receiveShadow
            geometry={nodes.Object_59.geometry}
            material={materials.voofer_tex1}
          />
          <mesh
            name="Object_6"
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.LOGOhoodCHRM_tex2}
          />
          <mesh
            name="Object_60"
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.material_58}
          />
          <mesh
            name="Object_61"
            castShadow
            receiveShadow
            geometry={nodes.Object_61.geometry}
            material={materials.material_59}
          />
          <mesh
            name="Object_7"
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.LOGOhood_tex2}
          />
          <mesh
            name="Object_8"
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.PLlogo_tex2}
          />
          <mesh
            name="Object_9"
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.POWEREDBYSUBARU}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/car.glb");

export default CarModel;
